aFile = readLines("CV_EN.txt")
library(tm)
myCorpus = Corpus(VectorSource(aFile))
myCorpus = tm_map(myCorpus, tolower)
myCorpus = tm_map(myCorpus, removePunctuation)
myCorpus = tm_map(myCorpus, removeNumbers)
#myCorpus = tm_map(myCorpus, removeWords, stopwords("french"))
myCorpus = tm_map(myCorpus, removeWords, stopwords("english"))
myCorpus <- tm_map(myCorpus, PlainTextDocument)
myDTM = TermDocumentMatrix(myCorpus, control = list(minWordLength = 1))
m = as.matrix(myDTM)
v = sort(rowSums(m), decreasing = TRUE)
library(wordcloud)
set.seed(1234)
wordcloud(names(v), v, min.freq = 5)